### ISSUE TITLE
[BUG] Supercharged links (0.11.0) sometimes fails to unload

### ISSUE THREAD

**Issue by FeralFlora** [mdelobelle/obsidian_supercharged_links#208]
Error in console:

```
Plugin failure: supercharged-links-obsidian TypeError: Cannot read properties of undefined (reading 'forEach')
    at SuperchargedLinks.onunload (main.ts:219:18)
    at e.unload (app.js:1:716024)
    at e.<anonymous> (app.js:1:2037547)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at e.unloadPlugin (app.js:1:2037452)
    at e.<anonymous> (app.js:1:2040484)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at e.disablePlugin (app.js:1:2040358)
    at e.<anonymous> (app.js:1:2041140)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at e.disablePluginAndSave (app.js:1:2040986)
    at e.eval (plugin:quick-plugin-switcher:2672:28)
    at e.wrapper [as disablePluginAndSave] (index.js:20:24)
    at t.<anonymous> (app.js:1:2727226)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.changeCallback (app.js:1:2727036)
    at t.setValue (app.js:1:1320051)
    at t.onClick (app.js:1:1320274)
    ```
    
    Debug info:
   ```
    SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Prism v3.4.1
	Snippets enabled: 25
	Restricted mode: off
	Plugins installed: 120
	Plugins enabled: 96
 ```

**Comment by FeralFlora** [comment]
> Hmm, I cannot reproduce this. Are you using the quick-plugin-switcher to enable/disable SL?

Yes, it was inconsistent for me too. Happened first after I used Quick plugin switcher, but then also from the community plugin settings page.
